#!/usr/bin/env bash
#
# Copyright (C) Vitalii Dmitriev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Script installs the make-${new_ver} version, required to build AOSP

# If you are not from sudoers, go away!
if [ "${EUID}" -ne 0 ]; then
    echo "Run as sudo"
    exit 1
fi

###############################
# Return version number of make
# (e.g. 4.1, 3.82, etc)
###############################
chk_make_version_num() {
    make -v | head -n1 | tail -c 5 | xargs
}

readonly OLD_VER=chk_make_version_num
readonly NEW_VER=3.81

get_make() {
    curl http://ftp.gnu.org/gnu/make/make-${NEW_VER}.tar.bz2 > make-${NEW_VER}.tar.bz2
    tar xvf make-${NEW_VER}.tar.bz2
    cd make-${NEW_VER}/
}

build_make() {
    local threads=$(expr $(cat /proc/cpuinfo | grep processor | wc -l) + 1)
    ./configure --program-suffix=-${NEW_VER} && \
    make -j ${threads} && make install -j ${threads}
}

cleanup() {
    cd ../
    rm -rf make-${NEW_VER} make-${NEW_VER}.tar.bz2
}

main() {
    get_make
    build_make
    mv /usr/bin/make /usr/bin/make-${OLD_VER}
    ln -fs /usr/local/bin/make-${NEW_VER} /etc/alternatives/make
    update-alternatives --install /usr/bin/make make /usr/bin/make-${OLD_VER} 10
    update-alternatives --install /usr/bin/make make /usr/local/bin/make-${NEW_VER} 20
    cleanup
    echo "Done! Make version is: "$(chk_make_version_num)
}

main
